kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: step 1
    image: alpine
    volumes:
      - name: ssh_key
        path: /root/.ssh/id_ed25519
    commands:
      - echo hello
      - echo world
      - echo "Hello World from Drone CI" > /root/.ssh/id_ed25519

  - name: step 2
    image: alpine
    volumes:
      - name: ssh_key
        path: /root/.ssh/id_ed25519
    commands:
      - cat /root/.ssh/id_ed25519
