kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: Add SSH key to volumes
    image: alpine
    environment:
      SSH_KEY:
        from_secret: SSH_KEY
    volumes:
      - name: ssh_key
        path: /root/.ssh/
    commands:
      - mkdir -p /root/.ssh
      - echo $SSH_KEY > /root/.ssh/id_ed25519

  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: fullstacker/ipstack
      tags: latest

volumes:
  - name: ssh_key
    temp: {}
